@API_HostAddress = http://localhost:5253
# @API_HostAddress = http://192.168.10.107:8429/ApiTriWall/ http://192.168.20.2:8082


#http://localhost/APITRIWALL http://192.168.10.2/AddOnProgram
#http://localhost:8429/BarCodeBackEnd/HeloWorld

###

GET {{API_HostAddress}}/HeloWord
###

POST {{API_HostAddress}}/getQuery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6ImMzMmU5Yjk3LTA5YTYtNDQ2ZS1hNzY3LTI1MTc3OGQ0Y2VhMyIsImlkIjoiYWRtaW4xMC8xMC8yMDI0IDA4OjU3OjM2IiwibmJmIjoxNzI4NTUwNjU2LCJleHAiOjE3MjkxNTU0NTYsImlhdCI6MTcyODU1MDY1Nn0.LDkCBkie3VRThQ2KOxsDHz6AOGa3DlpeCWlJ5KiNlUo

{
    "storeName": "_USP_CALLTRANS_EWTRANSACTION",
    "dbType": "LayoutPrinter",
    "par1": "GOODRECEIPTPO",
    "par2": "",
    "par3": "",
    "par4": "",
    "par5": ""
}

###

GET {{API_HostAddress}}/api/user
Content-Type: application/json

{
}

###

POST {{API_HostAddress}}/api/login
Content-Type: application/json

{
}

###

POST {{API_HostAddress}}/goodReceiptPo
Content-Type: application/json

{
    "VendorCode": "V-A001-00",
    "ContactPersonCode": 0,
    "VendorNo": "",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "isDraft": true,
    "Lines": [
        {
            "ItemCode": "RIIP4401390INP",
            "Qty": 10,
            "Price": 10,
            "VatCode": "P00",
            "WarehouseCode": "AS01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/deliveryOrders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6ImM5NDdhYzEyLTFjNWMtNGU3Mi1hMDZmLTg5YjQ4NjJmOWJkZSIsImlkIjoiYWRtaW4xMC8zMS8yMDI0IDAzOjE4OjM3IiwibmJmIjoxNzMwMzQ0NzE3LCJleHAiOjE3MzA5NDk1MTcsImlhdCI6MTczMDM0NDcxN30.4slwgI0TucLNM3zSXQoUz27G8GEFopUm1L1053bnQTQ
Content-Type: application/json

{
  "customerCode": "C-A001-01",
  "contactPersonCode": "0",
  "numAtCard": "",
  "series": "183",
  "docDate": "2024-09-10T15:34:44.185+07:00",
  "taxDate": "2024-09-10T00:00:00",
  "remarks": "test1",
  "isDraft": true,
  "lines": [
    {
      "itemCode": "BATCH-TEST",
      "itemName": "123",
      "qty": 1,
      "lineNum": 1,
      "price": 1,
      "vatCode": "S00",
      "warehouseCode": "AS01",
      "manageItem": "B",
      "baseEntry": 0,
      "baseLine": 0,
      "batches": [
        {
          "batchCode": "BATCH-0002",
          "qty": 1,
          "qtyAvailable": 5,
          "expDate": "2024-09-10T00:00:00+07:00",
          "manfectureDate": "2024-09-10T00:00:00+07:00",
          "admissionDate": "2024-09-10T00:00:00+07:00",
          "lotNo": "",
          "onSelectedBatchOrSerial": []
        }
      ],
      "serials": []
    }
  ]
}

###

POST {{API_HostAddress}}/purchaseOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/issueForProduction
Content-Type: application/json

{
  "Series": "336",
  "Remarks": "",
  "DocDate": "2024-07-02T00:00:00",
  "Lines": [
    {
      "DocNum": "729",
      "LineNum": 0,
      "BaseLineNum": 0,
      "ItemCode": "TEST-B-01",
      "ItemName": "Batch",
      "Qty": 2,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "B",
      "Batches": [
        {
          "BatchCode": "test21",
          "Qty": 2,
          "ExpDate": "2024-06-25T00:00:00",
          "ManfectureDate": "2024-07-02T00:00:00+07:00",
          "AdmissionDate": "2024-07-02T00:00:00+07:00",
          "LotNo": "",
          "QtyAvailable": 0,
          "OnSelectedBatchOrSerial": []
        }
      ],
      "Serials": null
    },
    {
      "DocNum": "730",
      "LineNum": 0,
      "BaseLineNum": 0,
      "ItemCode": "TEST-B-01",
      "ItemName": "Batch",
      "Qty": 2,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "B",
      "Batches": [
        {
          "BatchCode": "test21",
          "Qty": 2,
          "ExpDate": "2024-06-25T00:00:00",
          "ManfectureDate": "2024-07-02T00:00:00+07:00",
          "AdmissionDate": "2024-07-02T00:00:00+07:00",
          "LotNo": "",
          "QtyAvailable": 0,
          "OnSelectedBatchOrSerial": []
        }
      ],
      "Serials": null
    },
    {
      "DocNum": "729",
      "LineNum": 0,
      "BaseLineNum": 1,
      "ItemCode": "TEST-S-01",
      "ItemName": "Serial",
      "Qty": 1,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "S",
      "Batches": null,
      "Serials": [
        {
          "SerialCode": "t2123t1",
          "Qty": 1,
          "MfrNo": "",
          "MfrDate": "1899-12-30T00:00:00",
          "ExpDate": "1899-12-30T00:00:00",
          "OnSelectedBatchOrSerial": [
            {
              "ItemCode": "TEST-S-01",
              "Qty": "0",
              "SerialBatch": "t2123t1",
              "MfrSerialNo": "",
              "ExpDate": "12/30/1899 00:00:00",
              "MrfDate": "12/30/1899 00:00:00",
              "Type": "Serial",
              "LineNum": null
            }
          ]
        }
      ]
    },
    {
      "DocNum": "730",
      "LineNum": 0,
      "BaseLineNum": 1,
      "ItemCode": "TEST-S-01",
      "ItemName": "Serial",
      "Qty": 1,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "S",
      "Batches": null,
      "Serials": [
        {
          "SerialCode": "t2123t2",
          "Qty": 1,
          "MfrNo": "",
          "MfrDate": "1899-12-30T00:00:00",
          "ExpDate": "1899-12-30T00:00:00",
          "OnSelectedBatchOrSerial": [
            {
              "ItemCode": "TEST-S-01",
              "Qty": "0",
              "SerialBatch": "t2123t2",
              "MfrSerialNo": "",
              "ExpDate": "12/30/1899 00:00:00",
              "MrfDate": "12/30/1899 00:00:00",
              "Type": "Serial",
              "LineNum": null
            }
          ]
        }
      ]
    }
  ]
}


###

POST {{API_HostAddress}}/return
Content-Type: application/json

{
  "CustomerCode":"C003",
  "ContactPersonCode":"0",
  "NumAtCard":"",
  "Series":"192",
  "DocDate":"2024-07-19T16:23:30.303+07:00",
  "TaxDate":"2024-07-19T00:00:00",
  "Remarks":"",
  "IsDraft":false,
  "Lines":[
    {
      "ItemCode":"TEST-B-01",
      "ItemName":"Batch",
      "Qty":1,
      "LineNum":1,
      "Price":1,
      "VatCode":"S00",
      "WarehouseCode":"RS02",
      "ManageItem":"B",
      "BaseEntry":0,
      "BaseLine":0,
      "Batches":[
        {
          "BatchCode":"W-01",
          "Qty":1,
          "QtyAvailable":10,
          "ExpDate":"2024-07-09T00:00:00",
          "ManfectureDate":"2024-07-09T00:00:00",
          "AdmissionDate":"2024-07-19T00:00:00+07:00",
          "LotNo":"",
          "OnSelectedBatchOrSerial":[
            {
              "ItemCode":"TEST-B-01",
              "Qty":"10",
              "SerialBatch":"W-01",
              "MfrSerialNo":"",
              "ExpDate":"07/09/2024 00:00:00",
              "MrfDate":"07/09/2024 00:00:00",
              "Type":"Batch",
              "LineNum":null
            }
          ]
        }
      ]
      ,"Serials":[]
    }
  ]
}

###

POST {{API_HostAddress}}/arCreditMemo
Content-Type: application/json

{
  "CustomerCode": "A020-00",
  "ContactPersonCode": 0,
  "NumAtCard": "",
  "Series": "170",
  "DocDate": "2024-07-30T11:15:05.899+07:00",
  "TaxDate": "2024-05-23T00:00:00",
  "Remarks": "",
  "IsDraft": false,
  "Lines": [
    {
      "ItemCode": "20",
      "ItemName": "10",
      "Qty": 1,
      "LineNum": 1,
      "Price": 2,
      "VatCode": "S00",
      "WarehouseCode": "RS02",
      "ManageItem": "S",
      "BaseEntry": 99,
      "BaseLine": 0,
      "Batches": [],
      "Serials": [
        {
          "SerialCode": "1232",
          "Qty": 1,
          "MfrNo": "1232",
          "MfrDate": null,
          "ExpDate": null,
          "OnSelectedBatchOrSerial": [
            {
              "ItemCode": "20",
              "Qty": "1",
              "SerialBatch": "123",
              "MfrSerialNo": "123",
              "ExpDate": "",
              "MrfDate": "",
              "Type": "Serial",
              "LineNum": "1"
            }
          ]
        }
      ]
    }
  ]
}

###

POST {{API_HostAddress}}/inventoryCounting
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6ImMzMmU5Yjk3LTA5YTYtNDQ2ZS1hNzY3LTI1MTc3OGQ0Y2VhMyIsImlkIjoiYWRtaW4xMC8xMC8yMDI0IDA4OjU3OjM2IiwibmJmIjoxNzI4NTUwNjU2LCJleHAiOjE3MjkxNTU0NTYsImlhdCI6MTcyODU1MDY1Nn0.LDkCBkie3VRThQ2KOxsDHz6AOGa3DlpeCWlJ5KiNlUo

{
  "docEntry": 54,
  "createTime": "16:49",
  "createDate": "2024-10-16T16:05:54.108+07:00",
  "otherRemark": "",
  "ref2": "",
  "series": "241000001",
  "inventoryCountingType": "Single Count",
  "counterId": 0,
  "lines": [
    {
      "itemCode": "BATCH-TEST",
      "itemName": "123",
      "whsCode": "AS01",
      "qty": 12,
      "qtyCounted": 1,
      "counted": "",
      "lineNum": 0,
      "manageItem": "B",
      "countId": 0,
      "binEntry": 0,
      "uom": "Manual",
      "batches": [
        {
          "itemCode": "BATCH-TEST",
          "conditionBatch": "new",
          "batchCode": "123",
          "qty": 1,
          "qtyAvailable": 0,
          "expireDate": "2024-10-16T00:00:00",
          "manufactureDate": "2024-10-16T00:00:00",
          "admissionDate": "2024-10-16T00:00:00",
          "lotNo": "",
          "binEntry": 0,
          "isBatchNew": "",
          "onSelectedBatchOrSerial": []
        }
      ],
      "serials": []
    }
  ]
}


###

POST {{API_HostAddress}}/inventoryCounting
Content-Type: application/json

{
    "docEntry": 40,
    "createTime": "16:21",
    "createDate": "2024-01-16T00:00:00",
    "otherRemark": "",
    "ref2": "",
    "series": "240100004",
    "inventoryCountingType": "Multiple Count",
    "counterId": 0,
    "lines": [
        {
            "itemCode": "IM-GC-0001",
            "itemName": "Formular glue conventional",
            "whsCode": "RM01",
            "qty": 1129.317,
            "qtyCounted": 2,
            "counted": "",
            "lineNum": 1,
            "manageItem": "N",
            "countId": 0,
            "binEntry": 0,
            "uom": "Manual",
            "batches": [],
            "serials": []
        }
    ]
}

###

POST {{API_HostAddress}}/receiptFromProduction/returnComponent
Content-Type: application/json

{
  "Series":"327",
  "Remarks":"",
  "DocDate":"2024-09-15T00:00:00",
  "Lines":[
    {
      "DocNum":"812",
      "LineNum":0,
      "BaseLineNum":0,
      "ItemCode":"BATCH-TEST",
      "ItemName":"123",
      "Qty":0.181818,
      "QtyRequire":11,
      "QtyPlan":1,
      "QtyManual":1,
      "QtyLost":1,
      "Price":0,
      "WhsCode":"RS02",
      "UomName":"Manual Batch",
      "ManageItem":"B",
      "Type":2,
      "Batches":[
        {
          "BatchCode":"BATCH-3",
          "Qty":0.181818,
          "QtyManual":0,
          "QtyLost":0,
          "ExpDate":"1899-12-30T00:00:00",
          "ManfectureDate":"1899-12-30T00:00:00",
          "AdmissionDate":"2024-09-15T00:00:00+07:00",
          "LotNo":"",
          "QtyAvailable":0,
          "OnSelectedBatchOrSerial":[],
          "OnSelectedProductionOrder":[],
          "OnSelectedType":[
            {"Id":1,"Name":"Auto"}]
        }
      ],
      "Serials":null,
      "ItemNones":null
    },
    {
      "DocNum":"810",
      "LineNum":0,
      "BaseLineNum":0,
      "ItemCode":"BATCH-TEST",
      "ItemName":"123",
      "Qty":0.727273,
      "QtyRequire":11,
      "QtyPlan":6,
      "QtyManual":0,
      "QtyLost":0.8,
      "Price":0,
      "WhsCode":"RS02",
      "UomName":"Auto Batch",
      "ManageItem":"B",
      "Type":2,
      "Batches":[
        {
          "BatchCode":"BATCH-3",
          "Qty":0.727273,
          "QtyManual":0,
          "QtyLost":0,
          "ExpDate":"1899-12-30T00:00:00",
          "ManfectureDate":"1899-12-30T00:00:00",
          "AdmissionDate":"2024-09-15T00:00:00+07:00",
          "LotNo":"",
          "QtyAvailable":0,
          "OnSelectedBatchOrSerial":[],
          "OnSelectedProductionOrder":[],
          "OnSelectedType":[
            {"Id":1,"Name":"Auto"}
          ]
        }
      ],
      "Serials":null,
      "ItemNones":null
    },
    {
      "DocNum":"811",
      "LineNum":0,
      "BaseLineNum":0,
      "ItemCode":"BATCH-TEST",
      "ItemName":"123",
      "Qty":1.090909,
      "QtyRequire":11,
      "QtyPlan":6,
      "QtyManual":0,
      "QtyLost":1.2,
      "Price":0,
      "WhsCode":"RS02",
      "UomName":"Auto Batch",
      "ManageItem":"B",
      "Type":2,
      "Batches":[
        {
          "BatchCode":"BATCH-3",
          "Qty":1.090909,
          "QtyManual":0,
          "QtyLost":0,
          "ExpDate":"1899-12-30T00:00:00",
          "ManfectureDate":"1899-12-30T00:00:00",
          "AdmissionDate":"2024-09-15T00:00:00+07:00",
          "LotNo":"",
          "QtyAvailable":0,
          "OnSelectedBatchOrSerial":[],
          "OnSelectedProductionOrder":[],
          "OnSelectedType":[
            {"Id":1,"Name":"Auto"}
          ]
        }
      ],
      "Serials":null,
      "ItemNones":null
    }
  ]
}

###

POST {{API_HostAddress}}/receiptFromProduction/updateProcessProduction
Content-Type: application/json

{
  "data": [
    {
      "productionNo": 808,
      "processStage": "PR1",
      "status": "Yes"
    }
  ]
}


###
     
POST {{API_HostAddress}}/auth
Content-Type: application/json

{
    "Account": "admin",
    "Password": "1234"
}

###